### ISSUE TITLE
Extract audio (wav) from DLC

### ISSUE THREAD

**Issue by MauricioKruijer** [ctxis/Furby#2]
How can I extract audio files from the dlc's? Like this stuff https://github.com/ctxis/Furby/tree/master/audio/extracted_audio did you guys used the audio.bmp's to figure this out? 

audio.bmp created by https://github.com/Jeija/bluefluff/blob/master/util/visualize_audio.py

**Comment by pdjstone** [comment]
I've added the scripts I used to extract/convert the DLC audio to .wav. Take a look at the audioutils directory - they just use the a1800.dll library from the GeneralPlus conversion utility, so you'll need to run this on Windows.
